### ISSUE TITLE
请问有没有windows系统的部署方法

### ISSUE THREAD

**Issue by Akarinnnnnnn** [bytedance/music_source_separation#26]
对项目挺感兴趣, 不过在windows系统安装失败了, 请问下作者有没有这方面的解决方案?

**Comment by Akarinnnnnnn** [comment]
已经用wsl2安装解决了, 省去了很多不必要的麻烦.

**Comment by Heporis** [comment]
> 已经用wsl2安装解决了, 省去了很多不必要的麻烦.

能出个教程吗？我macOS每次pip install bytesep就会报错，真的没招了

**Comment by Heporis** [comment]
> 已经用wsl2安装解决了, 省去了很多不必要的麻烦.

救救孩子吧，已经搞了好几天了，我用macOS报错，虚拟机装个ubuntu安装还是报错，用wsl安装还是报错，鬼知道我以前是怎么在macOS上装好的😂
