### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by sophia1488** [bytedance/music_source_separation#27]
Hi! First, thanks for your contribution to music source separation!
Since I'd like to separate vocals & accompaniment using only 1 model, and the pre-trained model you provided has only one target, I decided to train it from scratch.
I also modify the code so that a validation set is added.

However, I cannot train it on 3 GTX 1080 with small batch size (<12), and I thought that the ResUNet_ismir doesn't require that much memory?  Or does it really need a lot of GPU memory?
Could you provide some insight, like how long it takes for you to train a model and how many GPU memory it requires?

Thank you a lot!

**Comment by qiuqiangkong** [comment]
Hi, please use ResUNet_subband model, it is 4x smaller and the performance
is close to the ResUNet system.

**Comment by sophia1488** [comment]
Thank you so much, though I later found that it was my preprocessing problem...
One other thing I'd like to ask is that is it normal to have negative SDR at epoch 8?

**Comment by qiuqiangkong** [comment]
Usually the SDR is positive after 1 epochs.

**Comment by sophia1488** [comment]
Got it, thanks!
