### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Heporis** [bytedance/music_source_separation#29]
Help me please! wuwuwu~
  Building wheel for h5py (setup.py) ... error

**Comment by Heporis** [comment]
How can I install h5py for macOS 10.15.7?

**Comment by Heporis** [comment]
how can I install hdf5 correctly?
Building wheel for h5py (setup.py) ... error

**Comment by Heporis** [comment]
Loading library to get version: libhdf5.dylib
  error: dlopen(libhdf5.dylib, 6): image not found

**Comment by qiuqiangkong** [comment]
Try pip install h5py?

**Comment by Heporis** [comment]
> Try pip install h5py?

pip install h5py没问题，但是pip install bytesep不行
 每次都是Building wheel for h5py (setup.py) ... error
![截屏2021-12-09 上午9 08 31](https://user-images.githubusercontent.com/51895154/145316172-e7e2268b-832c-44df-a63e-ea0093f6a8ed.png)
加了HDF5_DIR=/usr/local/Cellar/hdf5/1.12.1后
`    building 'h5py.defs' extension
    creating build/temp.macosx-10.15-x86_64-3.9
    creating build/temp.macosx-10.15-x86_64-3.9/private
    creating build/temp.macosx-10.15-x86_64-3.9/private/var
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823
    creating build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -DH5_USE_16_API -I./h5py -I/usr/local/Cellar/hdf5/1.12.1/include -I/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/lzf -I/usr/local/lib/python3.9/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c -o build/temp.macosx-10.15-x86_64-3.9/private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.o
    In file included from /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:725:
    In file included from ./h5py/api_compat.h:26:
    In file included from /usr/local/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /usr/local/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /usr/local/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
    /usr/local/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:16550:56: error: too few arguments to function call, expected 3, have 2
      __pyx_t_1 = H5Oget_info(__pyx_v_loc_id, __pyx_v_oinfo); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1509, __pyx_L1_error)
                  ~~~~~~~~~~~                              ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Opublic.h:497:8: note: 'H5Oget_info3' declared here
    H5_DLL herr_t H5Oget_info3(hid_t loc_id, H5O_info2_t *oinfo, unsigned fields);
           ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:16665:95: error: too few arguments to function call, expected 5, have 4
      __pyx_t_1 = H5Oget_info_by_name(__pyx_v_loc_id, __pyx_v_name, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1520, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~~~~                                                             ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Opublic.h:557:8: note: 'H5Oget_info_by_name3' declared here
    H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_info2_t *oinfo, unsigned fields,
           ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:16780:144: error: too few arguments to function call, expected 8, have 7
      __pyx_t_1 = H5Oget_info_by_idx(__pyx_v_loc_id, __pyx_v_group_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_n, __pyx_v_oinfo, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1531, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~~~                                                                                                               ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Opublic.h:631:8: note: 'H5Oget_info_by_idx3' declared here
    H5_DLL herr_t H5Oget_info_by_idx3(hid_t loc_id, const char *group_name, H5_index_t idx_type,
           ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:17815:100: error: too few arguments to function call, expected 6, have 5
      __pyx_t_1 = H5Ovisit(__pyx_v_obj_id, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1630, __pyx_L1_error)
                  ~~~~~~~~                                                                             ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Opublic.h:1326:8: note: 'H5Ovisit3' declared here
    H5_DLL herr_t H5Ovisit3(hid_t obj_id, H5_index_t idx_type, H5_iter_order_t order, H5O_iterate2_t op,
           ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:17930:143: error: too few arguments to function call, expected 8, have 7
      __pyx_t_1 = H5Ovisit_by_name(__pyx_v_loc_id, __pyx_v_obj_name, __pyx_v_idx_type, __pyx_v_order, __pyx_v_op, __pyx_v_op_data, __pyx_v_lapl_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 1641, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~                                                                                                                ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Opublic.h:1492:8: note: 'H5Ovisit_by_name3' declared here
    H5_DLL herr_t H5Ovisit_by_name3(hid_t loc_id, const char *obj_name, H5_index_t idx_type,
           ^
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:21840:13: warning: assigning to 'void *' from 'const void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
      __pyx_t_1 = H5Pget_driver_info(__pyx_v_plist_id); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 2016, __pyx_L1_error)
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /private/var/folders/x1/1fd67kn91pddn94ch27h08th0000gn/T/pip-install-eb0041po/h5py_9578fe6d3dc8408bb773ea988cd77823/h5py/defs.c:34600:68: error: too few arguments to function call, expected 4, have 3
      __pyx_t_1 = H5Sencode(__pyx_v_obj_id, __pyx_v_buf, __pyx_v_nalloc); if (unlikely(PyErr_Occurred())) __PYX_ERR(0, 3303, __pyx_L1_error)
                  ~~~~~~~~~                                            ^
    /usr/local/Cellar/hdf5/1.12.1/include/H5Spublic.h:373:8: note: 'H5Sencode2' declared here
    H5_DLL herr_t H5Sencode2(hid_t obj_id, void *buf, size_t *nalloc, hid_t fapl);
           ^
    2 warnings and 6 errors generated.
    error: command '/usr/bin/clang' failed with exit code 1`

**Comment by qiuqiangkong** [comment]
Try this? *pip install h5py --upgrade*

It is suggested to use conda or virtualenv to manage the packages.

**Comment by Heporis** [comment]
> Try this? *pip install h5py --upgrade* It is suggested to use conda or virtualenv to manage the packages.
The same error. Tried many times with/without anaconda. 
I have installed it successfully on windows subsystem for linux. 
Confused macOS.🙄

**Comment by qiuqiangkong** [comment]
The installation works on my Mac. It looks like the problem is caused by
some environment settings.
