### ISSUE TITLE
WE ARE NOT ABLE TO (DOWNLOAD_CHECKPOINTS)

### ISSUE THREAD

**Issue by playdasegunda** [bytedance/music_source_separation#34]
Hi, I'm trying to use bytedance;

But I'm facing a problem when executing this command:

`python -m bytesep download_checkpoints`

But I'm getting the following error:

```
C:\Users\lucas\MSS>python -m bytesep download_checkpoints
usage: __main__.py [-h] {download-checkpoints,separate} ...
__main__.py: error: argument mode: invalid choice: 'download_checkpoints' (choose from 'download-checkpoints', 'separate')
```

I would like to know how I can solve this problem and can use bytedance in my songs,

Note, I was able to use it normally until October 2021, but now I'm not doing it anymore;

My thanks in advance, regards,
Lucas.

**Comment by Freddd13** [comment]
There are some typos in the current version. You can check out my pr.

**Comment by playdasegunda** [comment]
> There are some typos in the current version. You can check out my pr.

Thanks, I used your repository and it worked, however I'm facing this problem when separating some music, what can it be?

Does not work for cpu or cuda

![Screenshot_1](https://user-images.githubusercontent.com/97372669/148675774-de58c793-93a8-4f15-91fc-74274189b4bd.png)

**Comment by Freddd13** [comment]
What's your torch version?

Sent with a Spark
在 2022年1月9日 +0800 16:57，lucasbr15 ***@***.***>，写道：

**Comment by playdasegunda** [comment]
is **1.8.1+cu111**

**Comment by Freddd13** [comment]
I'm using torch 1.7.1 and didn't find such issues. Maybe you can try 1.7.1

Sent with a Spark
在 2022年1月9日 +0800 17:29，lucasbr15 ***@***.***>，写道：

**Comment by playdasegunda** [comment]
FIXED, thankyou!
