### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lucasdobr15** [bytedance/music_source_separation#4]
Hello, I have done all the installations and downloaded the templates, but when using the command 

"**python3 separate_scripts/separate.py**" or 
"**./separate_scripts/separate_accompaniment.sh "resources/vocals_accompaniment_10s.mp3" "sep_accompaniment.mp3**"

 I get the following error:

```
Traceback (most recent call last):
  File "bytesep/inference.py", line 13, in <module>
    from bytesep.models.lightning_modules import get_model_class
ModuleNotFoundError: No module named 'bytesep
```

How can I fix this? Thanks in advance.

**Comment by leminhnguyen** [comment]
Hi @lucasdobr15, In the head of `bytesep/inference.py` try to add the two lines below:

```python
import sys
sys.path.append('.')
```

**Comment by qiuqiangkong** [comment]
$ PYTHONPATH="./"$ export PYTHONPATH

**Comment by bubblegg** [comment]
> Hi @lucasdobr15, In the head of `separate_scripts/separate.py` or `bytesep/inference.py` try to add the two lines below:
> 
> ```python
> import sys
> sys.path.append('.')
> ```

This did not work at all for me...

**Comment by AK391** [comment]
also getting this error @qiuqiangkong

**Comment by leminhnguyen** [comment]
@bubblegg please take a look at my notebook: https://colab.research.google.com/drive/1OO1SBkhwPG8GyNuY8GdUQEpJDiRLmHLW?usp=sharing

**Comment by robotPin** [comment]
> > 嗨@lucasdobr15，在`separate_scripts/separate.py`或`bytesep/inference.py`尝试添加以下两行：
> > ```python
> > 导入 系统
> > 系统。路径。追加（'.'）
> > ```
> 
> 这对我来说根本不起作用......

卸载bytesep 0.0.1版
pip uninstall bytesep 
安装bytesep 0.0.2问题解决了
pip install bytesep
