### ISSUE TITLE
Run Example failed in windows10

### ISSUE THREAD

**Issue by BigCat20196** [bytedance/music_source_separation#42]
Hi Team, When I install bytesep according to the readdme, execute the demo command. 
```
python3 -m bytesep separate \
    --source_type="vocals" \
    --audio_path="./resources/vocals_accompaniment_10s.mp3" \
    --output_path="separated_results/output.mp3"
```

However,  I can't get the result and any error info.
![1648367704(1)](https://user-images.githubusercontent.com/51037443/160272366-1fe8b1d7-5112-4a8e-abbd-58abd78d96bc.png)

My env:
Windows10 
Python 3.7.5 (installed by conda)

I tried to use command line, PowerShell and git bash, and the results were the same.
Does it lack support for the windows ?

Appreciate if you can help this !

**Comment by Freddd13** [comment]
Use python instead of python3 under windows. If the problem still exists, you can try [my packed version](https://github.com/Freddd13/music-separation-gui)

**Comment by BigCat20196** [comment]
Hi @Freddd13, Thank you for your reply. Some errors were caused by my lack of `ffmpeg` before. Now it works well on the cmd and GUI.

**Comment by Freddd13** [comment]
> Hi @Freddd13, Thank you for your reply. Some errors were caused by my lack of `ffmpeg` before. Now it works well on the cmd and GUI.

I remember that GUI version should have contained a compact ffmpeg which will be provoked by a relative address.
